### ISSUE TITLE
Expression can generate errors

### ISSUE THREAD

**Issue by AndersonVidal** [Guardians-DSC/iarl-backend#15]
https://github.com/Guardians-DSC/iarl/blob/c7f5c6d9d0f78e13468acbab8200cd2fed15a775/controllers/login.js#L7
In javascript, empty strings have a false boolean type, as well as undefined and null data. 
In this case, an expression that would cover the undefined and null cases would be:
`if (req.body.username || req.body.password) {`

**Comment by AndersonVidal** [comment]
Correcting:
`if (!req.body.username || !req.body.password) {`

**Comment by dfquaresma** [comment]
Seems like a design discussion. We must choose the easiest to read, more readable. What do you guys think?

**Comment by danielrcoura** [comment]
I think the way: ```if (!req.body.username || !req.body.password) {``` seems simpler and readable
